import { Cinzel, Cinzel_Decorative, Outfit } from "next/font/google";
import "./globals.css";
import { TopBar } from "./_components/TopBar";
import { Header } from "./_components/Header";
import { Footer } from "./_components/Footer";
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const cinzel = Cinzel_Decorative({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: "700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        <TopBar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
